import {
	AdminPanelSettings,
	Anchor,
	DirectionsBoat,
	Feedback,
	Help,
	Message,
	Public,
} from '@mui/icons-material';

import { NavigationConfig } from '../types/navigationTypes';

export const navigationConfig: NavigationConfig = {
	topNav: [
		{
			title: 'Map',
			href: '/mda-ui/map/',
			disabled: false,
			icon: Public,
			ariaLabel: 'map',
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Messages',
			href: '/mda-ui/messages/',
			disabled: false,
			icon: Message,
			ariaLabel: 'messages',
			badgeColor: 'error',
			badgeCount: 0,
		},
		// {
		// 	title: 'Notifications',
		// 	href: '/mda-ui/notifications/',
		// 	disabled: false,
		// 	icon: Notifications,
		// 	ariaLabel: 'notifications',
		// },
	],
	leftSideDrawerNav: [
		{
			title: 'Map',
			href: '/mda-ui/map/',
			icon: Public,
			ariaLabel: 'map',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Messages',
			href: '/mda-ui/messages/',
			disabled: false,
			icon: Message,
			ariaLabel: 'messages',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 1,
		},
		{
			title: 'Vessel Information',
			href: '/mda-ui/vessel-information/',
			disabled: false,
			icon: DirectionsBoat,
			ariaLabel: 'vessel information',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Port Information',
			href: '/mda-ui/port-information/',
			disabled: false,
			icon: Anchor,
			ariaLabel: 'port information',
			bottom: false,
			badgeColor: 'warning',
			badgeCount: 1,
		},
		{
			title: 'Admin',
			href: '/mda-ui/admin/',
			icon: AdminPanelSettings,
			ariaLabel: 'admin',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Help',
			href: '/mda-ui/help/',
			icon: Help,
			ariaLabel: 'help',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Feedback',
			href: '/mda-ui/feedback/',
			icon: Feedback,
			ariaLabel: 'feedback',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
	],
};
